select * from mytable ;

 #what is the total revenue generated by male and female customers
select gender ,  sum(purchase_amount) as revenue from mytable
group by gender ;

#which customer used discount but still spent more than average purchase amount
select customer_id , purchase_amount from mytable
where discount_applied = 'yes' and purchase_amount >= ( select avg(purchase_amount) from mytable); 

#which are the top 5 product with highest avg rating?
select item_purchased , avg( review_rating) as "Avg product rating " from mytable
group by item_purchased
order by avg( review_rating) desc 
limit 5;

#Compare the avg purchase amount between standard and express shipping.
select shipping_type , avg(purchase_amount)  from mytable
where shipping_type in ('standard', 'express')
group by shipping_type;

#do subscribed spend more ? compare avg spend and total revenue between subscribers and non- subscribers
select subscription_status , count(customer_id) as "total customer" , avg(purchase_amount)  as "avg spend " , 
sum(purchase_amount) as "total revenue"
 from mytable
 group by subscription_status
 order by avg(purchase_amount) , sum(purchase_amount) desc;
 
 #which 5 product have the highest percentage of purchases with discounts applied??
 select item_purchased , 
 round(sum(case when discount_applied = 'yes' then 1 else 0 end )/COUNT(*) *100,2) as discount_rate
 from mytable
 group by item_purchased
 order by discount_rate desc
 limit 5;
 
 # segment customers into new , returning and loyal based on their total 
 #number of prev purchases and show the count of each segment
 with customer_type as (
 select customer_id , previous_purchases , 
 case 
 when previous_purchases = 1 then 'New'
 when previous_purchases BETWEEN 2 and 10 then 'Returning'
 else 'loyal'
 end as customer_segment 
 from mytable
 )
 select customer_segment , count(*) as " Number of customers" 
 from customer_type
 group by customer_segment;

 # what are the top 3 most purchased product within each category?
 with item_counts as ( 
 select category , 
 item_purchased, 
 COUNT( customer_id) as total_orders ,
 row_number() over ( partition by category order by count(customer_id)  desc) as item_rank
 from mytable
 group by category , item_purchased
 )
 select item_rank , category , item_purchased , total_orders
 from item_counts
 where item_rank <= 3;
 
 #are customers who are repeat buyers ( more than 5 prev purchases )also likely to subscribe?
 select  subscription_status , count(customer_id) as 'repeat buyers' from mytable
 where previous_purchases > 5
 group by subscription_status;
 
 # what is the revenue contibution of eah age group
 select age_group , sum(purchase_amount) as 'total revenue'  from mytable
 group by age_group
 order by sum(purchase_amount) desc;